"""
app_ui.py — Streamlit dashboard for the pet-detector YOLO model.
Run with: streamlit run app_ui.py
"""

import os
import tempfile
from collections import Counter
from pathlib import Path

import pandas as pd
import streamlit as st
from PIL import Image
from ultralytics import YOLO

MODEL_PATH = os.environ.get("MODEL_PATH", "weights/best.pt")
ZONE_LOG_PATH = os.environ.get("ZONE_LOG_PATH", "zone_events.csv")


@st.cache_resource
def load_model(model_path: str):
    return YOLO(model_path)


def run_detection(model, image_path: str, conf: float):
    results = model.predict(source=image_path, conf=conf, save=False)
    result = results[0]

    counts = Counter()
    for cls_idx in result.boxes.cls:
        class_name = model.names[int(cls_idx)]
        counts[class_name] += 1

    return result, counts


def load_events(log_path: str) -> pd.DataFrame:
    """Read the zone_detector.py event log CSV into a DataFrame.

    Not cached with @st.cache_data since the CSV can change between runs
    of zone_detector.py and this file is small enough that re-reading it
    on every rerun/refresh is cheap.
    """
    path = Path(log_path)
    if not path.exists():
        return pd.DataFrame(columns=["timestamp", "frame_num", "video_source", "class_name", "track_id", "event", "zone_id"])
    return pd.read_csv(path)


def render_image_detection_tab(model, conf: float):
    st.write("Upload a photo and the model will detect and count the animals in it.")
    uploaded_file = st.file_uploader("Upload an image", type=["jpg", "jpeg", "png"])

    if uploaded_file is not None:
        with tempfile.NamedTemporaryFile(delete=False, suffix=".jpg") as tmp:
            tmp.write(uploaded_file.read())
            tmp_path = tmp.name

        with st.spinner("Running detection..."):
            result, counts = run_detection(model, tmp_path, conf)

        annotated = result.plot()[:, :, ::-1]
        st.image(annotated, caption="Detections", use_container_width=True)

        st.subheader("Counts")
        if not counts:
            st.write("No animals detected. Try lowering the confidence threshold.")
        else:
            total = sum(counts.values())
            cols = st.columns(len(counts))
            for col, (class_name, count) in zip(cols, sorted(counts.items(), key=lambda x: -x[1])):
                col.metric(class_name, count)
            st.write(f"**Total animals detected:** {total}")


def render_zone_events_tab():
    st.write(f"Reading zone crossing events from `{ZONE_LOG_PATH}` (generated by `zone_detector.py`).")

    if st.button("Refresh"):
        st.rerun()

    events = load_events(ZONE_LOG_PATH)

    if events.empty:
        st.info("No zone events found yet. Run `zone_detector.py --source your_video.mp4` first to generate `zone_events.csv`.")
        return

    st.subheader("Summary")
    summary = (
        events.groupby(["class_name", "event"])
        .size()
        .reset_index(name="count")
        .sort_values(["class_name", "event"])
    )
    cols = st.columns(len(summary)) if len(summary) <= 6 else None
    if cols:
        for col, row in zip(cols, summary.itertuples()):
            col.metric(f"{row.class_name} {row.event}", row.count)
    else:
        st.dataframe(summary, use_container_width=True, hide_index=True)

    st.subheader("All events")
    st.dataframe(
        events.sort_values("timestamp", ascending=False),
        use_container_width=True,
        hide_index=True,
    )


def main():
    st.set_page_config(page_title="Pet Detector", page_icon="🐾", layout="centered")
    st.title("🐾 Pet Detector")

    if not Path(MODEL_PATH).exists():
        st.error(f"Model weights not found at `{MODEL_PATH}`.")
        return

    model = load_model(MODEL_PATH)
    conf = st.slider("Confidence threshold", min_value=0.05, max_value=0.95, value=0.25, step=0.05)

    tab_detect, tab_zone = st.tabs(["Image Detection", "Zone Events"])
    with tab_detect:
        render_image_detection_tab(model, conf)
    with tab_zone:
        render_zone_events_tab()


if __name__ == "__main__":
    main()
